'use server';

import { revalidatePath } from 'next/cache';
import { createClient } from '@/lib/supabase/server';
import { addDays, dayKey } from '@/lib/domain/dates';
import { earnedXp, withStreakBonus } from '@/lib/domain/xp';
import { daysFromEntries, streakDays } from '@/lib/domain/streak';
import { toKind } from '@/lib/data/map';

export interface LogResult {
  ok: true;
  /** XP actually awarded, after the streak bonus. */
  xp: number;
  level: number;
  leveledUp: boolean;
}
export interface LogFailure {
  ok: false;
  error: string;
}
export type LogOutcome = LogResult | LogFailure;

/** Streaks are worth XP, so the server works them out rather than trusting the client. */
async function currentStreak(
  supabase: Awaited<ReturnType<typeof createClient>>,
  today: string,
): Promise<number> {
  const { data, error } = await supabase
    .from('log_entries')
    .select('created_at, source')
    .gte('created_at', `${addDays(today, -60)}T00:00:00Z`);

  if (error || !data) return 0;
  // Rows arrive in snake_case; daysFromEntries works on the domain shape.
  return streakDays(
    daysFromEntries(data.map((row) => ({ createdAt: row.created_at, source: row.source }))),
    today,
  );
}

function isUuid(value: unknown): value is string {
  return (
    typeof value === 'string' &&
    /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(value)
  );
}

/** One optional line of text. Never required, never blocks the action. */
function cleanNote(note: unknown): string | null {
  if (typeof note !== 'string') return null;
  const trimmed = note.trim();
  return trimmed === '' ? null : trimmed.slice(0, 280);
}

export interface CompleteTaskInput {
  /** Generated by the client so a replayed offline mutation lands once. */
  entryId: string;
  taskId: string;
  note?: string;
  /** Timer tasks only. */
  minutes?: number;
}

export async function completeTask(input: CompleteTaskInput): Promise<LogOutcome> {
  if (!isUuid(input.entryId) || !isUuid(input.taskId)) {
    return { ok: false, error: 'Ongeldige taak. Ververs de pagina en probeer opnieuw.' };
  }

  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return { ok: false, error: 'Je sessie is verlopen. Log opnieuw in.' };

  const { data: task, error: taskError } = await supabase
    .from('tasks')
    .select('*')
    .eq('id', input.taskId)
    .maybeSingle();

  if (taskError) return { ok: false, error: `Kon de taak niet laden: ${taskError.message}` };
  if (!task) return { ok: false, error: 'Deze taak bestaat niet meer.' };

  const kind = toKind(task.kind);
  let minutes: number | null = null;

  if (kind === 'timer') {
    const raw = input.minutes;
    if (typeof raw !== 'number' || !Number.isFinite(raw) || raw < 0) {
      return { ok: false, error: 'De timer leverde geen geldige tijd op. Start hem opnieuw.' };
    }
    minutes = Math.round(raw);
  }

  const today = dayKey(new Date());
  const streak = await currentStreak(supabase, today);
  const xp =
    kind === 'timer'
      ? earnedXp({ kind: 'timer', value: task.value, minutes: minutes ?? 0 }, streak)
      : earnedXp({ kind: 'check', value: task.value }, streak);

  const { data: before } = await supabase
    .from('skills')
    .select('level')
    .eq('id', task.skill_id)
    .maybeSingle();

  const { data: after, error } = await supabase
    .rpc('log_completion', {
      p_id: input.entryId,
      p_skill: task.skill_id,
      p_task: task.id,
      p_title: task.title,
      p_xp: xp,
      p_minutes: minutes,
      p_note: cleanNote(input.note),
      p_source: kind === 'timer' ? 'timer' : 'manual',
      p_created_at: new Date().toISOString(),
    });

  if (error) return { ok: false, error: `Opslaan mislukte: ${error.message}` };
  if (!after) return { ok: false, error: 'Opslaan gaf geen bevestiging terug. Probeer opnieuw.' };

  revalidatePath('/vandaag');
  return {
    ok: true,
    xp,
    level: after.level,
    leveledUp: after.level > (before?.level ?? after.level),
  };
}

export interface QuickLogInput {
  entryId: string;
  skillId: string;
  title: string;
  xp: number;
  note?: string;
}

/** Records something that was never on the list. */
export async function quickLog(input: QuickLogInput): Promise<LogOutcome> {
  if (!isUuid(input.entryId) || !isUuid(input.skillId)) {
    return { ok: false, error: 'Kies eerst een vaardigheid.' };
  }

  const title = typeof input.title === 'string' ? input.title.trim() : '';
  if (title === '') return { ok: false, error: 'Geef kort op wat je gedaan hebt.' };

  if (!Number.isFinite(input.xp) || input.xp < 5 || input.xp > 150) {
    return { ok: false, error: 'Kies een waarde tussen 5 en 150 XP.' };
  }

  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return { ok: false, error: 'Je sessie is verlopen. Log opnieuw in.' };

  const today = dayKey(new Date());
  const streak = await currentStreak(supabase, today);
  const xp = withStreakBonus(Math.round(input.xp), streak);

  const { data: before } = await supabase
    .from('skills')
    .select('level')
    .eq('id', input.skillId)
    .maybeSingle();

  const { data: after, error } = await supabase
    .rpc('log_completion', {
      p_id: input.entryId,
      p_skill: input.skillId,
      p_task: null,
      p_title: title.slice(0, 120),
      p_xp: xp,
      p_minutes: null,
      p_note: cleanNote(input.note),
      p_source: 'quick',
      p_created_at: new Date().toISOString(),
    });

  if (error) return { ok: false, error: `Opslaan mislukte: ${error.message}` };
  if (!after) return { ok: false, error: 'Opslaan gaf geen bevestiging terug. Probeer opnieuw.' };

  revalidatePath('/vandaag');
  return {
    ok: true,
    xp,
    level: after.level,
    leveledUp: after.level > (before?.level ?? after.level),
  };
}
